# Table summary
df_1 <- read.csv(file = 'Desktop/SaYoPillow.csv')
df_2 <- read.csv(file = 'Desktop/Sleep_Analysis.csv')
df_3 <- read.csv(file = 'Desktop/BellaBeatInd.csv')
View(df_1)
View(df_2)
View(df_3)
library(stringr)
library(dplyr)
library(tidyverse)
